-- AIAS Memphis Design Studio community backend
-- Run this once in a chapter-owned Supabase project.
-- IMPORTANT: use only the browser-safe publishable/anon key in the website config.
-- Never place a service_role key in this repository.

create extension if not exists pgcrypto;

create table if not exists public.community_designs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  title text not null check (char_length(title) between 1 and 80),
  designer text not null check (char_length(designer) between 1 and 80),
  caption text not null default '' check (char_length(caption) <= 280),
  design_code text not null check (char_length(design_code) between 8 and 24000),
  status text not null default 'published' check (status in ('pending','published','hidden')),
  featured boolean not null default false,
  parent_id uuid references public.community_designs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.community_design_likes (
  design_id uuid not null references public.community_designs(id) on delete cascade,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (design_id, user_id)
);

create table if not exists public.community_design_reports (
  id bigint generated by default as identity primary key,
  design_id uuid not null references public.community_designs(id) on delete cascade,
  reporter_id uuid not null,
  reason text not null check (char_length(reason) between 5 and 500),
  created_at timestamptz not null default now(),
  unique (design_id, reporter_id)
);

create index if not exists community_designs_status_created_idx
  on public.community_designs(status, created_at desc);
create index if not exists community_designs_owner_idx
  on public.community_designs(owner_id, created_at desc);
create index if not exists community_design_likes_design_idx
  on public.community_design_likes(design_id);

alter table public.community_designs enable row level security;
alter table public.community_design_likes enable row level security;
alter table public.community_design_reports enable row level security;

-- New Supabase projects may not expose new tables to the Data API automatically.
grant select on public.community_designs to anon, authenticated;
grant insert, update, delete on public.community_designs to authenticated;
grant select on public.community_design_likes to anon, authenticated;
grant insert, delete on public.community_design_likes to authenticated;
grant insert on public.community_design_reports to authenticated;
grant usage, select on sequence public.community_design_reports_id_seq to authenticated;

-- Everyone may see only published community designs.
drop policy if exists "Public can view published community designs" on public.community_designs;
create policy "Public can view published community designs"
on public.community_designs for select
to anon, authenticated
using (status = 'published');

-- Anonymous-authenticated visitors may publish only rows they own.
-- featured is reserved for chapter administrators in the Supabase dashboard.
drop policy if exists "Users can publish their own designs" on public.community_designs;
create policy "Users can publish their own designs"
on public.community_designs for insert
to authenticated
with check (
  owner_id = (select auth.uid())
  and featured = false
  and status in ('pending','published')
);

-- A visitor can edit/hide/delete only designs created by the same anonymous auth identity.
drop policy if exists "Users can update their own designs" on public.community_designs;
create policy "Users can update their own designs"
on public.community_designs for update
to authenticated
using (owner_id = (select auth.uid()))
with check (
  owner_id = (select auth.uid())
  and featured = false
  and status in ('pending','published','hidden')
);

drop policy if exists "Users can delete their own designs" on public.community_designs;
create policy "Users can delete their own designs"
on public.community_designs for delete
to authenticated
using (owner_id = (select auth.uid()));

-- Likes are public to read, but each visitor can create/remove only their own like.
drop policy if exists "Public can view design likes" on public.community_design_likes;
create policy "Public can view design likes"
on public.community_design_likes for select
to anon, authenticated
using (true);

drop policy if exists "Users can like as themselves" on public.community_design_likes;
create policy "Users can like as themselves"
on public.community_design_likes for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can remove their own likes" on public.community_design_likes;
create policy "Users can remove their own likes"
on public.community_design_likes for delete
to authenticated
using (user_id = (select auth.uid()));

-- Reports are write-only for visitors. Chapter admins review them in Supabase.
drop policy if exists "Users can report as themselves" on public.community_design_reports;
create policy "Users can report as themselves"
on public.community_design_reports for insert
to authenticated
with check (reporter_id = (select auth.uid()));

-- Optional helper trigger for updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists community_designs_set_updated_at on public.community_designs;
create trigger community_designs_set_updated_at
before update on public.community_designs
for each row execute function public.set_updated_at();

-- After running this file:
-- 1. In Supabase Auth settings, enable Anonymous Sign-Ins.
-- 2. Copy Project URL + publishable key into data/community-backend.json.
-- 3. Set enabled=true.
-- 4. mode="auto" publishes immediately; mode="moderated" inserts as pending.
-- 5. Never expose service_role credentials in GitHub or browser code.
