-- AIAS Memphis Design Studio community backend
-- Run this once in a chapter-owned Supabase project.
-- IMPORTANT: use only the browser-safe publishable key in the website config.
-- Never place a secret/service_role key in this repository.

create extension if not exists pgcrypto;

create table if not exists public.community_settings (
  id boolean primary key default true check (id = true),
  mode text not null default 'auto' check (mode in ('auto','moderated'))
);
insert into public.community_settings (id, mode)
values (true, 'auto')
on conflict (id) do nothing;

create table if not exists public.community_designs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  title text not null check (char_length(title) between 1 and 80),
  designer text not null check (char_length(designer) between 1 and 80),
  caption text not null default '' check (char_length(caption) <= 280),
  design_code text not null check (
    char_length(design_code) between 8 and 24000
    and design_code ~ '^[A-Za-z0-9_-]+$'
  ),
  status text not null default 'published' check (status in ('pending','published','hidden')),
  featured boolean not null default false,
  parent_id uuid references public.community_designs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.community_design_likes (
  design_id uuid not null references public.community_designs(id) on delete cascade,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (design_id, user_id)
);

create table if not exists public.community_design_reports (
  id bigint generated by default as identity primary key,
  design_id uuid not null references public.community_designs(id) on delete cascade,
  reporter_id uuid not null,
  reason text not null check (char_length(reason) between 5 and 500),
  created_at timestamptz not null default now(),
  unique (design_id, reporter_id)
);

create index if not exists community_designs_status_created_idx
  on public.community_designs(status, created_at desc);
create index if not exists community_designs_owner_idx
  on public.community_designs(owner_id, created_at desc);
create index if not exists community_design_likes_design_idx
  on public.community_design_likes(design_id);

alter table public.community_settings enable row level security;
alter table public.community_designs enable row level security;
alter table public.community_design_likes enable row level security;
alter table public.community_design_reports enable row level security;

-- New Supabase projects may not expose new tables to the Data API automatically.
-- These are the minimum browser permissions; RLS still decides which rows are allowed.
grant select on public.community_settings to anon, authenticated;
grant select on public.community_designs to anon, authenticated;
grant insert, delete on public.community_designs to authenticated;
revoke update on public.community_designs from authenticated;
grant select on public.community_design_likes to anon, authenticated;
grant insert, delete on public.community_design_likes to authenticated;
grant insert on public.community_design_reports to authenticated;
grant usage, select on sequence public.community_design_reports_id_seq to authenticated;

-- Visitors may read the active community mode, but cannot change it from the browser.
drop policy if exists "Public can read community mode" on public.community_settings;
create policy "Public can read community mode"
on public.community_settings for select
to anon, authenticated
using (id = true);

-- Published designs are visible to everyone. A signed-in anonymous owner can also read
-- their own pending row so the insert can return its final database-enforced status.
drop policy if exists "Public can view published community designs" on public.community_designs;
create policy "Public can view published community designs"
on public.community_designs for select
to anon, authenticated
using (
  status = 'published'
  or owner_id = (select auth.uid())
);

-- The database, not browser JavaScript, chooses published vs pending.
create or replace function public.apply_community_publish_mode()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  publish_mode text;
begin
  select mode into publish_mode
  from public.community_settings
  where id = true;

  new.featured := false;
  new.status := case when publish_mode = 'moderated' then 'pending' else 'published' end;
  return new;
end;
$$;

revoke all on function public.apply_community_publish_mode() from public;

drop trigger if exists community_designs_apply_mode on public.community_designs;
create trigger community_designs_apply_mode
before insert on public.community_designs
for each row execute function public.apply_community_publish_mode();

-- Anonymous-authenticated visitors may insert only rows they own. The BEFORE trigger above
-- has already normalized status and featured values before this WITH CHECK is evaluated.
drop policy if exists "Users can publish their own designs" on public.community_designs;
create policy "Users can publish their own designs"
on public.community_designs for insert
to authenticated
with check (
  owner_id = (select auth.uid())
  and featured = false
  and status in ('pending','published')
);

-- Browser users do not need UPDATE permission. They may delete only their own posts.
drop policy if exists "Users can update their own designs" on public.community_designs;
drop policy if exists "Users can delete their own designs" on public.community_designs;
create policy "Users can delete their own designs"
on public.community_designs for delete
to authenticated
using (owner_id = (select auth.uid()));

-- Likes are public to read, but each visitor can create/remove only their own like.
drop policy if exists "Public can view design likes" on public.community_design_likes;
create policy "Public can view design likes"
on public.community_design_likes for select
to anon, authenticated
using (true);

drop policy if exists "Users can like as themselves" on public.community_design_likes;
create policy "Users can like as themselves"
on public.community_design_likes for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can remove their own likes" on public.community_design_likes;
create policy "Users can remove their own likes"
on public.community_design_likes for delete
to authenticated
using (user_id = (select auth.uid()));

-- Reports are write-only for visitors. Chapter admins review them in Supabase.
drop policy if exists "Users can report as themselves" on public.community_design_reports;
create policy "Users can report as themselves"
on public.community_design_reports for insert
to authenticated
with check (reporter_id = (select auth.uid()));

-- Prevent one anonymous browser identity from flooding the live wall.
create or replace function public.enforce_community_design_post_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (
    select count(*)
    from public.community_designs
    where owner_id = new.owner_id
      and created_at > now() - interval '24 hours'
  ) >= 10 then
    raise exception 'Community post limit reached: maximum 10 designs per 24 hours';
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_community_design_post_limit() from public;

drop trigger if exists community_designs_post_limit on public.community_designs;
create trigger community_designs_post_limit
before insert on public.community_designs
for each row execute function public.enforce_community_design_post_limit();

-- Keep updated_at current for administrator edits in the dashboard.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists community_designs_set_updated_at on public.community_designs;
create trigger community_designs_set_updated_at
before update on public.community_designs
for each row execute function public.set_updated_at();

-- After running this file:
-- 1. In Supabase Auth settings, enable Anonymous Sign-Ins.
-- 2. Copy Project URL + PUBLISHABLE key into data/community-backend.json.
-- 3. Set enabled=true.
-- 4. Keep data/community-backend.json mode aligned with community_settings.mode for UI wording.
--    Database enforcement comes from community_settings, not the browser.
-- 5. To switch modes later, run one of these in Supabase SQL editor:
--      update public.community_settings set mode = 'auto' where id = true;
--      update public.community_settings set mode = 'moderated' where id = true;
-- 6. Never expose a Supabase secret/service_role credential in GitHub or browser code.
-- 7. CAPTCHA can be added later, but do not enable it until the browser flow is configured
--    to supply captchaToken during signInAnonymously().
